In [1]:
# Training of pRNN ansatz for generation of Symmetric Polynomials

import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR) #stop displaying tensorflow warnings

import importnb

import numpy as np
import matplotlib.pyplot as plt

with importnb.Notebook('pRNN_homo_sample.ipynb'):
    from pRNN_homo_sample import RNNWavefunction

Generated Samples:
[[5 0 0 0 0 0 0 0 0]
 [2 0 0 2 1 0 0 0 0]
 [1 1 3 0 0 0 0 0 0]
 [0 1 3 0 0 0 1 0 0]
 [0 5 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 3 0 0]
 [2 3 0 0 0 0 0 0 0]
 [3 0 1 0 1 0 0 0 0]
 [4 1 0 0 0 0 0 0 0]
 [1 1 3 0 0 0 0 0 0]]
Generated Samples:
[-15.403661 -16.041853 -15.369361 -15.676439 -15.403015 -15.704596
 -15.352121 -15.737051 -15.505245 -15.369361]


In [2]:
# Computes local energies given a set of computational basis vectors sampled according to the pRNN wavefunction probability

def symPoly_local_energies(a,b,Nc, samples, model):
    """ Local energies of a system of Nc**2 interacting bosonic oscillators.
    Returns: The local energies that correspond to the "samples"
    Inputs:
    - a,b: define the Gauge generator
    - Nc: rank of the matrix group
    - samples: (numsamples, Nc**2)
    - model: The RNN wavefunction model instance
    """

    numsamples = samples.shape[0]  # Extracts number of samples

    local_energies = np.zeros((numsamples), dtype=np.float64)  # Initialize local energy to zero for each sample
    
    energy_samples= np.zeros((2*Nc,numsamples), dtype=np.float64) # Array of energies to zero for each sample
    #print(energy_samples)
    queue_samples= np.zeros((1+2*Nc,numsamples,Nc*Nc), dtype=np.float64)  # Array of vector states to zero for each sample
    log_probs= np.zeros((1+2*Nc)*numsamples, dtype=np.float64) # Array of log probs for each vector state for each sample
    
    queue_samples[0]=samples

    # Evaluation of local energy

    for c in range(Nc):  # +1 terms
        samplesT = np.copy(samples)
        
        energy_samples[c,:][samples[:, (a-1)*Nc+c] > 0]= 1
        energy_samples[c,:][samples[:, (a-1)*Nc+c] == 0]= 0

        #print(energy_samples[c,:])
        
        samplesT[:, (a-1)*Nc+c] -= 1
        samplesT[:, (b-1)*Nc+c] += 1
        
        queue_samples[1+c] = samplesT

    for c in range(Nc):  # -1 terms
        samplesT = np.copy(samples)

        energy_samples[c+Nc,:][samples[:, c*Nc+(b-1)] > 0]= -1
        energy_samples[c+Nc,:][samples[:, c*Nc+(b-1)] == 0]= 0
        
        #print(energy_samples[c+Nc,:])
        
        samplesT[:, c*Nc+(a-1)] += 1
        samplesT[:, c*Nc+(b-1)] -= 1
        
        queue_samples[1+Nc+c] = samplesT
 
    # Evaluate log probability of samples and of flipped sample vectors, according to pRNN amplitudes
    
    queue_samples_reshaped = np.reshape(queue_samples, [(1+2*Nc) * numsamples, Nc*Nc])
    len_sigmas = queue_samples_reshaped.shape[0]

    steps = np.ceil(len_sigmas / 25000)  # Maximum of 25000 configurations in batch size for memory reasons

    for i in range(int(steps)):
        cut = slice((i * len_sigmas) // int(steps), ((i + 1) * len_sigmas) // int(steps))
        log_probs[cut] = model.log_probability(queue_samples_reshaped[cut]) # Computes log probabilities slice-by-slice

    log_probs_reshaped = np.reshape(log_probs,[1+2*Nc,numsamples]) # Reshape log_probs putting in line all log probs related to a given sample
    amplitudes_ratio = np.exp(0.5 * log_probs_reshaped[1:, :] - 0.5 * log_probs_reshaped[0, :]) #Ratio of wavefunction amplitudes for each flipped over unflipped sample

    local_energies += np.sum(energy_samples*amplitudes_ratio,axis=0) # Adds local energy from non-diagonal terms 

    return local_energies

In [48]:
# Training of pRNN with VMC for energy minimization
# Can imposes penalty weight to loss function in order to fix total spin Jtarget - now commented
# Uses Adam optimizer
# Uses gradient decay

def train_rnn_wavefunction(model, Nc, num_epochs, learning_rate, num_samples):
    """
    Train the RNN wavefunction model to minimize the local energy.
    Parameters:
    - model: RNN-based wavefunction model
    - Nc rank of matrices (Nc*Nc matrix elements =  bosonic oscillators = variables in the polynomial)
    - num_epochs: int, number of training epochs
    - learning_rate: float, learning rate for optimization
    - num_samples: int, total number of samples per epoch
    """
    # Define initial learning rate, decay rate, and decay steps
    initial_learning_rate = learning_rate
    decay_rate = 0.5
    decay_steps = 250  # The step interval at which the learning rate is updated

    # Create an exponential decay schedule
    lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=initial_learning_rate,
    decay_steps=decay_steps,
    decay_rate=decay_rate,
    staircase=False  # If True, decay happens in discrete steps
    )

    # Use the schedule in an optimizer
    optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)
    
    energy_vec = [] # Stores avg energies during optimization for plot
    std_vec = [] # Stores std devs during optimization for plot
    avg_magnetization = [] # Stores average spin vector during optimization for plot

    for epoch in range(num_epochs):
        samples = model.sample(num_samples)  # Generate num_samples samples from the RNN wavefunction

        random_array =np.random.rand(Nc*Nc)
        #local_energies= np.array([tf.cast(random_array[(a-1)*Nc+b]*symPoly_local_energies(a,b,Nc,samples, model), dtype=tf.float32) for b in range(Nc) for a in range(Nc)]) # Compute local energy for every sample

        local_energies= tf.cast(symPoly_local_energies(1,1,Nc,samples, model), dtype=tf.float32) 

        with tf.GradientTape() as tape:
            log_probs = model.log_probability(samples)
            loss = tf.abs(tf.reduce_mean(log_probs * local_energies)-tf.reduce_mean(log_probs)*tf.reduce_mean(local_energies)) # Energy minimization loss
            
        gradients = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    
        avg_energy = np.mean(local_energies)
        std_energy = np.std(local_energies)
        
        energy_vec.append(avg_energy)
        std_vec.append(std_energy)
        avg_magnetization.append(np.mean(tf.reshape(samples,[-1])))
        
        print(f"Epoch {epoch + 1}/{num_epochs}, Energy: {avg_energy:.6f}, Std Dev: {std_energy:.6f}, Mean Spin: {np.mean(samples):.6f}")

            #if epoch % 50 ==0:
            #    print("Time step = "+str(epoch) )
        print(samples.shape[0])
    
    print(samples.numpy())
    
    return energy_vec, std_vec, avg_magnetization

In [53]:
# Define the system size (number of timesteps), number of GRU units, and other parameters
Nc =2 # Gauge group rank

system_size = Nc*Nc # Number of time steps = spin sites
system_charge =  1 # Polynomial degree (= power of matrix)
units = 100  # Number of (hidden) units in the GRU layer
input_dim = system_charge+1  # Input dimension (e.g., spin-1/2 system)
output_dim = system_charge+1  # Output dimension (e.g., 2 possible states per timestep)
seed = 123


# Generate random samples
numsamples = 40

# Create the RNNWavefunction model
rnn_wavefunction = RNNWavefunction(system_size=Nc*Nc, units=units, input_dim=input_dim, output_dim=output_dim,seed =seed)

samples = rnn_wavefunction.sample(numsamples)

energies, std_devs, order_param = train_rnn_wavefunction(rnn_wavefunction,Nc, num_epochs=200,learning_rate= 0.05,num_samples=numsamples)

Epoch 1/200, Energy: 0.150000, Std Dev: 0.653835, Mean Spin: 0.250000
40
Epoch 2/200, Energy: 0.175000, Std Dev: 0.627993, Mean Spin: 0.250000
40
Epoch 3/200, Energy: 0.175000, Std Dev: 0.586835, Mean Spin: 0.250000
40
Epoch 4/200, Energy: 0.000000, Std Dev: 0.632456, Mean Spin: 0.250000
40
Epoch 5/200, Energy: 0.275000, Std Dev: 0.591079, Mean Spin: 0.250000
40
Epoch 6/200, Energy: 0.300000, Std Dev: 0.600000, Mean Spin: 0.250000
40
Epoch 7/200, Energy: 0.325000, Std Dev: 0.565133, Mean Spin: 0.250000
40
Epoch 8/200, Energy: 0.150000, Std Dev: 0.572276, Mean Spin: 0.250000
40
Epoch 9/200, Energy: 0.325000, Std Dev: 0.607762, Mean Spin: 0.250000
40
Epoch 10/200, Energy: 0.225000, Std Dev: 0.523808, Mean Spin: 0.250000
40
Epoch 11/200, Energy: -0.025000, Std Dev: 0.611862, Mean Spin: 0.250000
40
Epoch 12/200, Energy: 0.150000, Std Dev: 0.476970, Mean Spin: 0.250000
40
Epoch 13/200, Energy: 0.175000, Std Dev: 0.627993, Mean Spin: 0.250000
40
Epoch 14/200, Energy: 0.200000, Std Dev: 0.556